In [1]:
# A good practice is to put required external packages in the first cell of the file
# and use "%pip" so that you install packages for all your kernels
%pip install pandas

Requirement already satisfied: pandas in c:\users\skelet0n_0ff\appdata\local\programs\python\python312\lib\site-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in c:\users\skelet0n_0ff\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2.1.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\skelet0n_0ff\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\skelet0n_0ff\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\skelet0n_0ff\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: six>=1.5 in c:\users\skelet0n_0ff\appdata\local\programs\python\python312\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [1]:
# Followed by a list of imports in the next cell
import pandas as pd
import numpy as np               # Conventional short name for the package

#### Load your dataset into a DataFrame

In [2]:
data = pd.read_csv("./data/CoffeeAndCodeLT2018 - CoffeeAndCodeLT2018.csv")

#### Preview the top five rows of your DataFrame

In [3]:
data.head()

,CodingHours,CoffeeCupsPerDay,CoffeeTime,CodingWithoutCoffee,CoffeeType,CoffeeSolveBugs,Gender,Country,AgeRange
0,8,2,Before coding,Yes,Caffè latte,Sometimes,Female,Lebanon,18 to 29
1,3,2,Before coding,Yes,Americano,Yes,Female,Lebanon,30 to 39
2,5,3,While coding,No,Nescafe,Yes,Female,Lebanon,18 to 29
3,8,2,Before coding,No,Nescafe,Yes,Male,Lebanon,NaN
4,10,3,While coding,Sometimes,Turkish,No,Male,Lebanon,18 to 29

#### You can also preview the bottom rows and specify the number of rows to show

In [4]:
data.tail(3)     # Three last rows

,CodingHours,CoffeeCupsPerDay,CoffeeTime,CodingWithoutCoffee,CoffeeType,CoffeeSolveBugs,Gender,Country,AgeRange
97,10,3,Before coding,Yes,Cappuccino,Yes,Male,Lebanon,Under 18
98,2,2,While coding,Sometimes,Espresso (Short Black),Sometimes,Female,Lebanon,18 to 29
99,10,4,Before coding,Sometimes,Double Espresso (Doppio),Sometimes,Male,Lebanon,18 to 29

#### Get a more detailed overview. This dataset has some null values

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   CodingHours          100 non-null    int64
 1   CoffeeCupsPerDay     100 non-null    int64
 2   CoffeeTime           100 non-null    object
 3   CodingWithoutCoffee  100 non-null    object
 4   CoffeeType           99 non-null     object
 5   CoffeeSolveBugs      100 non-null    object
 6   Gender               100 non-null    object
 7   Country              100 non-null    object
 8   AgeRange             98 non-null     object
dtypes: int64(2), object(7)
memory usage: 7.2+ KB

#### You can look through a range of rows in your DataFrame like this

In [6]:
data[:50]

,CodingHours,CoffeeCupsPerDay,CoffeeTime,CodingWithoutCoffee,CoffeeType,CoffeeSolveBugs,Gender,Country,AgeRange
0,8,2,Before coding,Yes,Caffè latte,Sometimes,Female,Lebanon,18 to 29
1,3,2,Before coding,Yes,Americano,Yes,Female,Lebanon,30 to 39
2,5,3,While coding,No,Nescafe,Yes,Female,Lebanon,18 to 29
3,8,2,Before coding,No,Nescafe,Yes,Male,Lebanon,NaN
4,10,3,While coding,Sometimes,Turkish,No,Male,Lebanon,18 to 29
5,8,2,While coding,Sometimes,Nescafe,Yes,Male,Lebanon,30 to 39
6,5,2,While coding,Yes,Nescafe,Sometimes,Male,Lebanon,NaN
7,10,4,Before coding,Sometimes,Turkish,Sometimes,Male,Lebanon,18 to 29
8,10,2,While coding,Yes,American Coffee,Sometimes,Male,Lebanon,30 to 39
9,10,2,While coding,Yes,Nescafe,No,Male,Lebanon,30 to 39
10,10,3,While coding,Sometimes,American Coffee,Sometimes,Male,Lebanon,30 to 39
11,2,3,Before coding,Sometimes,Turkish,Yes,Male,Lebanon,30 to 39
12,8,2,Before and while coding,No,Nescafe,Yes,Male,Lebanon,30 to 39
13,9,3,While coding,Sometimes,Nescafe,Yes,Male,Lebanon,30 to 39
14,6,1,Before coding,Yes,Nescafe,Sometimes,Male,Lebanon,18 to 29
15,6,3,While coding,No,Americano,Yes,Female,Lebanon,30 to 39
16,10,3,While coding,Sometimes,American Coffee,Sometimes,Male,Lebanon,30 to 39
17,6,4,While coding,Yes,Turkish,Sometimes,Male,Lebanon,30 to 39
18,8,3,While coding,No,Nescafe,No,Male,Lebanon,18 to 29
19,3,1,In the morning,Yes,Nescafe,Sometimes,Female,Lebanon,30 to 39
20,3,3,While coding,Yes,Espresso (Short Black),Sometimes,Male,Lebanon,18 to 29
21,9,5,While coding,Sometimes,Nescafe,Yes,Male,Lebanon,18 to 29
22,4,2,While coding,Sometimes,American Coffee,Sometimes,Male,Lebanon,18 to 29
23,8,3,While coding,No,Turkish,No,Male,Lebanon,40 to 49
24,5,3,While coding,Sometimes,Cappuccino,Sometimes,Male,Lebanon,Under 18
25,6,3,While coding,Yes,Nescafe,No,Female,Lebanon,30 to 39
26,7,4,Before coding,Sometimes,Espresso (Short Black),No,Male,Lebanon,30 to 39
27,8,4,While coding,Sometimes,Turkish,Yes,Male,Lebanon,30 to 39
28,7,1,Before coding,Yes,Nescafe,Yes,Male,Lebanon,30 to 39
29,2,2,While coding,Sometimes,American Coffee,Sometimes,Male,Lebanon,40 to 49
30,10,6,All the time,No,American Coffee,Yes,Male,Lebanon,30 to 39
31,2,2,While coding,No,Nescafe,Sometimes,Female,Lebanon,18 to 29
32,9,2,Before coding,Sometimes,Nescafe,Sometimes,Female,Lebanon,18 to 29
33,4,1,Before coding,Yes,Nescafe,No,Male,Lebanon,30 to 39
34,6,2,While coding,Sometimes,Espresso (Short Black),Sometimes,Male,Lebanon,18 to 29
35,2,2,While coding,Yes,American Coffee,No,Male,Lebanon,30 to 39
36,2,3,All the time,Sometimes,Turkish,Sometimes,Male,Lebanon,30 to 39
37,7,7,After coding,Yes,Turkish,Yes,Female,Lebanon,40 to 49
38,1,1,While coding,Yes,Cappuccino,Yes,Male,Lebanon,40 to 49
39,4,2,While coding,Yes,Turkish,No,Male,Lebanon,50 to 59
40,8,2,While coding,Sometimes,Turkish,No,Male,Lebanon,30 to 39
41,8,4,While coding,Sometimes,Turkish,Yes,Male,Lebanon,30 to 39
42,3,2,While coding,Sometimes,American Coffee,Sometimes,Female,Lebanon,30 to 39
43,10,6,While coding,Sometimes,NaN,No,Male,Lebanon,18 to 29
44,3,2,After coding,Yes,Espresso (Short Black),Sometimes,Male,Lebanon,40 to 49
45,7,2,While coding,Sometimes,American Coffee,No,Female,Lebanon,18 to 29
46,2,1,While coding,Sometimes,Caffè latte,No,Female,Lebanon,18 to 29
47,9,1,In the morning,Yes,Nescafe,No,Female,Lebanon,18 to 29
48,8,2,Before coding,No,Nescafe,No,Female,Lebanon,18 to 29
49,6,1,Before coding,Yes,Nescafe,No,Male,Lebanon,30 to 39

#### Display the selected column

In [7]:
data["CoffeeType"]

0                  Caffè latte
1                    Americano
2                      Nescafe
3                      Nescafe
4                      Turkish
                ...
95                     Nescafe
96                     Nescafe
97                  Cappuccino
98      Espresso (Short Black)
99    Double Espresso (Doppio)
Name: CoffeeType, Length: 100, dtype: object

#### Display several selected columns

Note the syntax — we pass in a **list** of desired columns names as an index

In [8]:
data[["CodingHours", "CoffeeCupsPerDay", "CoffeeType"]]

    CodingHours  CoffeeCupsPerDay                CoffeeType
0             8                 2               Caffè latte
1             3                 2                 Americano
2             5                 3                   Nescafe
3             8                 2                   Nescafe
4            10                 3                   Turkish
..          ...               ...                       ...
95            6                 2                   Nescafe
96            4                 1                   Nescafe
97           10                 3                Cappuccino
98            2                 2    Espresso (Short Black)
99           10                 4  Double Espresso (Doppio)

[100 rows x 3 columns]

#### You can also index rows with simple true-false statements

In [9]:
data[data["CodingHours"] > 7]     # Let's take a look at some hard-working ones :)

,CodingHours,CoffeeCupsPerDay,CoffeeTime,CodingWithoutCoffee,CoffeeType,CoffeeSolveBugs,Gender,Country,AgeRange
0,8,2,Before coding,Yes,Caffè latte,Sometimes,Female,Lebanon,18 to 29
3,8,2,Before coding,No,Nescafe,Yes,Male,Lebanon,NaN
4,10,3,While coding,Sometimes,Turkish,No,Male,Lebanon,18 to 29
5,8,2,While coding,Sometimes,Nescafe,Yes,Male,Lebanon,30 to 39
7,10,4,Before coding,Sometimes,Turkish,Sometimes,Male,Lebanon,18 to 29
8,10,2,While coding,Yes,American Coffee,Sometimes,Male,Lebanon,30 to 39
9,10,2,While coding,Yes,Nescafe,No,Male,Lebanon,30 to 39
10,10,3,While coding,Sometimes,American Coffee,Sometimes,Male,Lebanon,30 to 39
12,8,2,Before and while coding,No,Nescafe,Yes,Male,Lebanon,30 to 39
13,9,3,While coding,Sometimes,Nescafe,Yes,Male,Lebanon,30 to 39
16,10,3,While coding,Sometimes,American Coffee,Sometimes,Male,Lebanon,30 to 39
18,8,3,While coding,No,Nescafe,No,Male,Lebanon,18 to 29
21,9,5,While coding,Sometimes,Nescafe,Yes,Male,Lebanon,18 to 29
23,8,3,While coding,No,Turkish,No,Male,Lebanon,40 to 49
27,8,4,While coding,Sometimes,Turkish,Yes,Male,Lebanon,30 to 39
30,10,6,All the time,No,American Coffee,Yes,Male,Lebanon,30 to 39
32,9,2,Before coding,Sometimes,Nescafe,Sometimes,Female,Lebanon,18 to 29
40,8,2,While coding,Sometimes,Turkish,No,Male,Lebanon,30 to 39
41,8,4,While coding,Sometimes,Turkish,Yes,Male,Lebanon,30 to 39
43,10,6,While coding,Sometimes,NaN,No,Male,Lebanon,18 to 29
47,9,1,In the morning,Yes,Nescafe,No,Female,Lebanon,18 to 29
48,8,2,Before coding,No,Nescafe,No,Female,Lebanon,18 to 29
51,8,3,While coding,Sometimes,American Coffee,Yes,Male,Lebanon,18 to 29
52,8,2,Before coding,Sometimes,American Coffee,Yes,Male,Lebanon,18 to 29
57,10,8,While coding,No,Turkish,Sometimes,Male,Lebanon,18 to 29
58,8,2,While coding,Sometimes,Turkish,No,Male,Lebanon,18 to 29
62,8,2,While coding,Sometimes,Turkish,Sometimes,Male,Lebanon,18 to 29
64,8,4,While coding,No,American Coffee,Sometimes,Male,Lebanon,18 to 29
65,8,2,Before coding,Sometimes,American Coffee,Sometimes,Female,Lebanon,18 to 29
67,10,2,While coding,Sometimes,American Coffee,Yes,Male,Lebanon,18 to 29
68,8,4,Before and while coding,No,Turkish,Yes,Male,Lebanon,18 to 29
69,10,6,While coding,Sometimes,Double Espresso (Doppio),No,Male,Lebanon,30 to 39
71,10,8,All the time,No,American Coffee,Yes,Male,Lebanon,18 to 29
73,8,4,Before and while coding,Sometimes,Turkish,Sometimes,Male,Lebanon,30 to 39
76,8,2,While coding,Sometimes,Nescafe,Sometimes,Male,Lebanon,30 to 39
77,9,3,While coding,Sometimes,Nescafe,Sometimes,Female,Lebanon,18 to 29
84,10,2,While coding,Yes,American Coffee,No,Male,Lebanon,18 to 29
85,10,3,While coding,Sometimes,American Coffee,Sometimes,Male,Lebanon,18 to 29
88,9,7,All the time,No,Espresso (Short Black),Yes,Male,Lebanon,18 to 29
89,10,1,Before coding,Sometimes,American Coffee,Sometimes,Male,Lebanon,18 to 29
97,10,3,Before coding,Yes,Cappuccino,Yes,Male,Lebanon,Under 18
99,10,4,Before coding,Sometimes,Double Espresso (Doppio),Sometimes,Male,Lebanon,18 to 29

#### With selection you are able to create new DataFrames from existing ones

In [10]:
hard_workers = data[data["CodingHours"] > 7]

In [11]:
hard_workers.head(8)

,CodingHours,CoffeeCupsPerDay,CoffeeTime,CodingWithoutCoffee,CoffeeType,CoffeeSolveBugs,Gender,Country,AgeRange
0,8,2,Before coding,Yes,Caffè latte,Sometimes,Female,Lebanon,18 to 29
3,8,2,Before coding,No,Nescafe,Yes,Male,Lebanon,NaN
4,10,3,While coding,Sometimes,Turkish,No,Male,Lebanon,18 to 29
5,8,2,While coding,Sometimes,Nescafe,Yes,Male,Lebanon,30 to 39
7,10,4,Before coding,Sometimes,Turkish,Sometimes,Male,Lebanon,18 to 29
8,10,2,While coding,Yes,American Coffee,Sometimes,Male,Lebanon,30 to 39
9,10,2,While coding,Yes,Nescafe,No,Male,Lebanon,30 to 39
10,10,3,While coding,Sometimes,American Coffee,Sometimes,Male,Lebanon,30 to 39

In [12]:
hard_workers.info()

<class 'pandas.core.frame.DataFrame'>
Index: 42 entries, 0 to 99
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   CodingHours          42 non-null     int64
 1   CoffeeCupsPerDay     42 non-null     int64
 2   CoffeeTime           42 non-null     object
 3   CodingWithoutCoffee  42 non-null     object
 4   CoffeeType           41 non-null     object
 5   CoffeeSolveBugs      42 non-null     object
 6   Gender               42 non-null     object
 7   Country              42 non-null     object
 8   AgeRange             41 non-null     object
dtypes: int64(2), object(7)
memory usage: 3.3+ KB

#### Let's sort the values and put the most hard-working on top

In [13]:
hard_workers.sort_values("CodingHours", ascending=False)

,CodingHours,CoffeeCupsPerDay,CoffeeTime,CodingWithoutCoffee,CoffeeType,CoffeeSolveBugs,Gender,Country,AgeRange
7,10,4,Before coding,Sometimes,Turkish,Sometimes,Male,Lebanon,18 to 29
4,10,3,While coding,Sometimes,Turkish,No,Male,Lebanon,18 to 29
10,10,3,While coding,Sometimes,American Coffee,Sometimes,Male,Lebanon,30 to 39
9,10,2,While coding,Yes,Nescafe,No,Male,Lebanon,30 to 39
8,10,2,While coding,Yes,American Coffee,Sometimes,Male,Lebanon,30 to 39
99,10,4,Before coding,Sometimes,Double Espresso (Doppio),Sometimes,Male,Lebanon,18 to 29
43,10,6,While coding,Sometimes,NaN,No,Male,Lebanon,18 to 29
57,10,8,While coding,No,Turkish,Sometimes,Male,Lebanon,18 to 29
30,10,6,All the time,No,American Coffee,Yes,Male,Lebanon,30 to 39
16,10,3,While coding,Sometimes,American Coffee,Sometimes,Male,Lebanon,30 to 39
85,10,3,While coding,Sometimes,American Coffee,Sometimes,Male,Lebanon,18 to 29
84,10,2,While coding,Yes,American Coffee,No,Male,Lebanon,18 to 29
97,10,3,Before coding,Yes,Cappuccino,Yes,Male,Lebanon,Under 18
89,10,1,Before coding,Sometimes,American Coffee,Sometimes,Male,Lebanon,18 to 29
69,10,6,While coding,Sometimes,Double Espresso (Doppio),No,Male,Lebanon,30 to 39
71,10,8,All the time,No,American Coffee,Yes,Male,Lebanon,18 to 29
67,10,2,While coding,Sometimes,American Coffee,Yes,Male,Lebanon,18 to 29
13,9,3,While coding,Sometimes,Nescafe,Yes,Male,Lebanon,30 to 39
77,9,3,While coding,Sometimes,Nescafe,Sometimes,Female,Lebanon,18 to 29
47,9,1,In the morning,Yes,Nescafe,No,Female,Lebanon,18 to 29
21,9,5,While coding,Sometimes,Nescafe,Yes,Male,Lebanon,18 to 29
88,9,7,All the time,No,Espresso (Short Black),Yes,Male,Lebanon,18 to 29
32,9,2,Before coding,Sometimes,Nescafe,Sometimes,Female,Lebanon,18 to 29
5,8,2,While coding,Sometimes,Nescafe,Yes,Male,Lebanon,30 to 39
0,8,2,Before coding,Yes,Caffè latte,Sometimes,Female,Lebanon,18 to 29
3,8,2,Before coding,No,Nescafe,Yes,Male,Lebanon,NaN
12,8,2,Before and while coding,No,Nescafe,Yes,Male,Lebanon,30 to 39
58,8,2,While coding,Sometimes,Turkish,No,Male,Lebanon,18 to 29
51,8,3,While coding,Sometimes,American Coffee,Yes,Male,Lebanon,18 to 29
48,8,2,Before coding,No,Nescafe,No,Female,Lebanon,18 to 29
41,8,4,While coding,Sometimes,Turkish,Yes,Male,Lebanon,30 to 39
18,8,3,While coding,No,Nescafe,No,Male,Lebanon,18 to 29
27,8,4,While coding,Sometimes,Turkish,Yes,Male,Lebanon,30 to 39
40,8,2,While coding,Sometimes,Turkish,No,Male,Lebanon,30 to 39
23,8,3,While coding,No,Turkish,No,Male,Lebanon,40 to 49
52,8,2,Before coding,Sometimes,American Coffee,Yes,Male,Lebanon,18 to 29
73,8,4,Before and while coding,Sometimes,Turkish,Sometimes,Male,Lebanon,30 to 39
65,8,2,Before coding,Sometimes,American Coffee,Sometimes,Female,Lebanon,18 to 29
62,8,2,While coding,Sometimes,Turkish,Sometimes,Male,Lebanon,18 to 29
68,8,4,Before and while coding,No,Turkish,Yes,Male,Lebanon,18 to 29
64,8,4,While coding,No,American Coffee,Sometimes,Male,Lebanon,18 to 29
76,8,2,While coding,Sometimes,Nescafe,Sometimes,Male,Lebanon,30 to 39

#### How about the most hard-working and the most coffee-drinking?

In [14]:
hard_workers \
    .sort_values(["CodingHours", "CoffeeCupsPerDay"], ascending=False)

,CodingHours,CoffeeCupsPerDay,CoffeeTime,CodingWithoutCoffee,CoffeeType,CoffeeSolveBugs,Gender,Country,AgeRange
57,10,8,While coding,No,Turkish,Sometimes,Male,Lebanon,18 to 29
71,10,8,All the time,No,American Coffee,Yes,Male,Lebanon,18 to 29
30,10,6,All the time,No,American Coffee,Yes,Male,Lebanon,30 to 39
43,10,6,While coding,Sometimes,NaN,No,Male,Lebanon,18 to 29
69,10,6,While coding,Sometimes,Double Espresso (Doppio),No,Male,Lebanon,30 to 39
7,10,4,Before coding,Sometimes,Turkish,Sometimes,Male,Lebanon,18 to 29
99,10,4,Before coding,Sometimes,Double Espresso (Doppio),Sometimes,Male,Lebanon,18 to 29
4,10,3,While coding,Sometimes,Turkish,No,Male,Lebanon,18 to 29
10,10,3,While coding,Sometimes,American Coffee,Sometimes,Male,Lebanon,30 to 39
16,10,3,While coding,Sometimes,American Coffee,Sometimes,Male,Lebanon,30 to 39
85,10,3,While coding,Sometimes,American Coffee,Sometimes,Male,Lebanon,18 to 29
97,10,3,Before coding,Yes,Cappuccino,Yes,Male,Lebanon,Under 18
8,10,2,While coding,Yes,American Coffee,Sometimes,Male,Lebanon,30 to 39
9,10,2,While coding,Yes,Nescafe,No,Male,Lebanon,30 to 39
67,10,2,While coding,Sometimes,American Coffee,Yes,Male,Lebanon,18 to 29
84,10,2,While coding,Yes,American Coffee,No,Male,Lebanon,18 to 29
89,10,1,Before coding,Sometimes,American Coffee,Sometimes,Male,Lebanon,18 to 29
88,9,7,All the time,No,Espresso (Short Black),Yes,Male,Lebanon,18 to 29
21,9,5,While coding,Sometimes,Nescafe,Yes,Male,Lebanon,18 to 29
13,9,3,While coding,Sometimes,Nescafe,Yes,Male,Lebanon,30 to 39
77,9,3,While coding,Sometimes,Nescafe,Sometimes,Female,Lebanon,18 to 29
32,9,2,Before coding,Sometimes,Nescafe,Sometimes,Female,Lebanon,18 to 29
47,9,1,In the morning,Yes,Nescafe,No,Female,Lebanon,18 to 29
27,8,4,While coding,Sometimes,Turkish,Yes,Male,Lebanon,30 to 39
41,8,4,While coding,Sometimes,Turkish,Yes,Male,Lebanon,30 to 39
64,8,4,While coding,No,American Coffee,Sometimes,Male,Lebanon,18 to 29
68,8,4,Before and while coding,No,Turkish,Yes,Male,Lebanon,18 to 29
73,8,4,Before and while coding,Sometimes,Turkish,Sometimes,Male,Lebanon,30 to 39
18,8,3,While coding,No,Nescafe,No,Male,Lebanon,18 to 29
23,8,3,While coding,No,Turkish,No,Male,Lebanon,40 to 49
51,8,3,While coding,Sometimes,American Coffee,Yes,Male,Lebanon,18 to 29
0,8,2,Before coding,Yes,Caffè latte,Sometimes,Female,Lebanon,18 to 29
3,8,2,Before coding,No,Nescafe,Yes,Male,Lebanon,NaN
5,8,2,While coding,Sometimes,Nescafe,Yes,Male,Lebanon,30 to 39
12,8,2,Before and while coding,No,Nescafe,Yes,Male,Lebanon,30 to 39
40,8,2,While coding,Sometimes,Turkish,No,Male,Lebanon,30 to 39
48,8,2,Before coding,No,Nescafe,No,Female,Lebanon,18 to 29
52,8,2,Before coding,Sometimes,American Coffee,Yes,Male,Lebanon,18 to 29
58,8,2,While coding,Sometimes,Turkish,No,Male,Lebanon,18 to 29
62,8,2,While coding,Sometimes,Turkish,Sometimes,Male,Lebanon,18 to 29
65,8,2,Before coding,Sometimes,American Coffee,Sometimes,Female,Lebanon,18 to 29
76,8,2,While coding,Sometimes,Nescafe,Sometimes,Male,Lebanon,30 to 39

#### Adding data to the DataFrame

Let's count hours spent coding **and** drinkning coffee

In [18]:
# First off: select those who drink coffee while coding
code_and_drink = hard_workers[hard_workers["CoffeeTime"] == "While coding"]

code_and_drink.insert(
    2,
    "CoffeeCupsPerCoding",
    code_and_drink.map(
        lambda x: x["CodingHours"] / x["CoffeeCupsPerDay"] 
    )
)

code_and_drink.head()

TypeError: 'int' object is not subscriptable

#### Merging DataFrames

**Caution!** There are a lot of caveats with indexing (it should match perfectly to avoid null values) and merging is a resource-heavy operation by itself. Only use it when you really need it!

[More information](https://pandas.pydata.org/docs/user_guide/merging.html)

## Data Preprocessing

#### Our DataFrame has null values that render their rows useless

In [17]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   CodingHours          100 non-null    int64
 1   CoffeeCupsPerDay     100 non-null    int64
 2   CoffeeTime           100 non-null    object
 3   CodingWithoutCoffee  100 non-null    object
 4   CoffeeType           99 non-null     object
 5   CoffeeSolveBugs      100 non-null    object
 6   Gender               100 non-null    object
 7   Country              100 non-null    object
 8   AgeRange             98 non-null     object
dtypes: int64(2), object(7)
memory usage: 7.2+ KB

In [34]:
clean_data = data.dropna()
clean_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 97 entries, 0 to 99
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   CodingHours          97 non-null     int64
 1   CoffeeCupsPerDay     97 non-null     int64
 2   CoffeeTime           97 non-null     object
 3   CodingWithoutCoffee  97 non-null     object
 4   CoffeeType           97 non-null     object
 5   CoffeeSolveBugs      97 non-null     object
 6   Gender               97 non-null     object
 7   Country              97 non-null     object
 8   AgeRange             97 non-null     object
dtypes: int64(2), object(7)
memory usage: 7.6+ KB

##### It can sometimes help to instead fill null values

```python
clean_data_2 = data["AgeRange"].fillna(data["AgeRange"].mean())
```

##### However, we cannot calculate the mean of this column since its values are of String type

#### Data with no variation is pointless — delete them!

In [35]:
# Check if there are any countries other than Lebanon
len(clean_data[clean_data["Country"] != "Lebanon"])

0

#### "Country" column is safe to drop

In [36]:
clean_data = clean_data.drop(columns=["Country"])

clean_data.head()

,CodingHours,CoffeeCupsPerDay,CoffeeTime,CodingWithoutCoffee,CoffeeType,CoffeeSolveBugs,Gender,AgeRange
0,8,2,Before coding,Yes,Caffè latte,Sometimes,Female,18 to 29
1,3,2,Before coding,Yes,Americano,Yes,Female,30 to 39
2,5,3,While coding,No,Nescafe,Yes,Female,18 to 29
4,10,3,While coding,Sometimes,Turkish,No,Male,18 to 29
5,8,2,While coding,Sometimes,Nescafe,Yes,Male,30 to 39

#### Most columns hold text values that are clear, but are uncomfortable to count

In [37]:
for column in clean_data.columns:             # column property returns a list of column names in string
    print("\n" + column + "\n\t")
    print(clean_data[column].unique())        # Returns a list of unique values in a column
    print("-"*40)                             # Fun way to add delimiters

CodingHours

[ 8  3  5 10  2  9  6  4  7  1]
----------------------------------------

CoffeeCupsPerDay

[2 3 4 1 5 6 7 8]
----------------------------------------

CoffeeTime

['Before coding' 'While coding' 'Before and while coding' 'In the morning'
 'All the time' 'After coding' 'No specific time']
----------------------------------------

CodingWithoutCoffee

['Yes' 'No' 'Sometimes']
----------------------------------------

CoffeeType

['Caffè latte' 'Americano' 'Nescafe' 'Turkish' 'American Coffee'
 'Espresso (Short Black)' 'Cappuccino' 'Double Espresso (Doppio)']
----------------------------------------

CoffeeSolveBugs

['Sometimes' 'Yes' 'No']
----------------------------------------

Gender

['Female' 'Male']
----------------------------------------

AgeRange

['18 to 29' '30 to 39' '40 to 49' 'Under 18' '50 to 59']
----------------------------------------

In [38]:
clean_data["Gender"] = clean_data["Gender"].map({"Male": 0, "Female": 1})
clean_data.head()

,CodingHours,CoffeeCupsPerDay,CoffeeTime,CodingWithoutCoffee,CoffeeType,CoffeeSolveBugs,Gender,AgeRange
0,8,2,Before coding,Yes,Caffè latte,Sometimes,1,18 to 29
1,3,2,Before coding,Yes,Americano,Yes,1,30 to 39
2,5,3,While coding,No,Nescafe,Yes,1,18 to 29
4,10,3,While coding,Sometimes,Turkish,No,0,18 to 29
5,8,2,While coding,Sometimes,Nescafe,Yes,0,30 to 39

In [41]:
def integerize(column):
    replacements = {}
    i = 0
    for attribute in column.unique():
        replacements.update({attribute: i})
        i += 1
    return column.map(replacements)

In [43]:
clean_data["CoffeeTime"] = integerize(clean_data["CoffeeTime"])
clean_data.head()

,CodingHours,CoffeeCupsPerDay,CoffeeTime,CodingWithoutCoffee,CoffeeType,CoffeeSolveBugs,Gender,AgeRange
0,8,2,0,Yes,Caffè latte,Sometimes,1,18 to 29
1,3,2,0,Yes,Americano,Yes,1,30 to 39
2,5,3,1,No,Nescafe,Yes,1,18 to 29
4,10,3,1,Sometimes,Turkish,No,0,18 to 29
5,8,2,1,Sometimes,Nescafe,Yes,0,30 to 39

In [44]:
to_replace = ["CodingWithoutCoffee", "CoffeeType", "CoffeeSolveBugs", "AgeRange"]

for column in to_replace:
    clean_data[column] = integerize(clean_data[column])

clean_data.head()

,CodingHours,CoffeeCupsPerDay,CoffeeTime,CodingWithoutCoffee,CoffeeType,CoffeeSolveBugs,Gender,AgeRange
0,8,2,0,0,0,0,1,0
1,3,2,0,0,1,1,1,1
2,5,3,1,1,2,1,1,0
4,10,3,1,2,3,2,0,0
5,8,2,1,2,2,1,0,1

In [45]:
clean_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 97 entries, 0 to 99
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   CodingHours          97 non-null     int64
 1   CoffeeCupsPerDay     97 non-null     int64
 2   CoffeeTime           97 non-null     int64
 3   CodingWithoutCoffee  97 non-null     int64
 4   CoffeeType           97 non-null     int64
 5   CoffeeSolveBugs      97 non-null     int64
 6   Gender               97 non-null     int64
 7   AgeRange             97 non-null     int64
dtypes: int64(8)
memory usage: 6.8 KB

### Congratulations! We've just preprocessed our data for our research!